BigInteger calculator and interpreter
YelenaZvyagina/bigIntCalculator pull request #1
Opened 2021-10-22 23:32 UTC by YelenaZvyagina

2021-10-23 18:54 UTC, gsvgit requested changes

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/AST.fs
> +namespace bigIntCalculator
А почему неймспейсы и модули названы как-то не в .NET стиле? С маленьклй буквы.

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/Lexer.fsl
> +| number		{ Parser.NUM((LexBuffer<_>.LexemeString lexbuf).Trim() |> bigIntCalculator.bigIntFunctions.strToBigint) }
А зачем здесь ```Trim```? похоже на костыль какой-то. Числа впринципе не содержат пробелы по краям.

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/Parser.fsy
> +    | vname {failwith "parse error"}
Классные сообщения об ошибках.

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/Parser.fsy
> +    | expr SUB rexpr {AST.Sub($1, $3)}
А почему тут нету перебора вариантов с ошибками?

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/myList.fs
> +    let ml1Greater (ml1 : MyList<_>) (ml2 : MyList<_>) =
Что-то мне кажется, что это про числа, а не про списки.

2021-10-23 18:54 UTC, gsvgit commented on src/BigInt/myList.fs
> +    let rec toFirst (lst : MyList<_>) =
И это тоже не про списки.

2021-10-23 18:54 UTC, gsvgit commented on tests/BigInt.UnitTests/bigIntFunctionsTest.fs
> +                testProperty "isEqual test" <| fun _ ->
Я бы ещё от просто int64 тесты сделал. А то так не очень понятно, что Вы там перебрали. А так можно со стандартной арифметикой сравнить.

2021-10-23 18:54 UTC, gsvgit commented on tests/BigInt.UnitTests/bigIntFunctionsTest.fs
> +                testProperty "sum test" <| fun _ ->
Ну и здесь тоже можно добавить int64

2021-10-23 21:56 UTC, YelenaZvyagina commented on src/BigInt/Parser.fsy
> +    | expr SUB rexpr {AST.Sub($1, $3)}
А что Вы имеете в виду под перебором ошибок?

2021-10-24 09:23 UTC, gsvgit commented on src/BigInt/Parser.fsy
> +    | expr SUB rexpr {AST.Sub($1, $3)}
Ну вот в предыдущем правиле Вы попытались как-то перебрать случаи, которые приводят к ошибке (но не полностью, похоже).

2021-10-25 08:06 UTC, gsvgit requested changes

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +                pDict.["print"] <- (pDict.["print"] + (if num.[0] = '+' then num.[1..] else num) + "\n")
А что бы название функции не вынести в переменную. Много гжде используется. А что если захотим имя поменять?

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +            | _ -> failwith "Num expected"
А почему бы не сказать, кого получили?

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +        pDict.Add("print", "")
А зачем?

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +        | _ -> failwith "unexpected statement"
Скажите хоть, какой.

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Lexer.fsl
> +let number = sign + ('0' ' ' | digits)
И всё же. Откуда в числах пробелы?

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/Parser.fsy
> +    | KW_PRINT {failwith "parse error of print"}
А если я сюда DIV поставлю? Должно падать или нет?

Вообще, страное Вы что-то делаете. Таки малоинформативные ошибки парсер сам по себе выдавать умеет. Вы и ошибки информативнее не делаете, и жизнь себе усложняете. Если и делать что-то с ошибками, то почитайте хотя бы тут: https://stackoverflow.com/questions/7928438/meaningful-errors-during-parsing-with-fsyacc

2021-10-25 08:06 UTC, gsvgit commented on src/BigInt/bigIntFunctions.fs
> +        sysListToMyList ( List.rev (myListToSystemList ml) )
А почему у Вас функции для списков в длинных числах?

2021-10-25 08:06 UTC, gsvgit commented on tests/BigInt.UnitTests/bigIntFunctionsTest.fs
> +                    let x = int64 ( (rand.Next()) * Int32.MaxValue )
А почему у Вас ни один из property-tests не использует свои аргументы?

2021-10-27 11:12 UTC, gsvgit requested changes

2021-10-27 11:12 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +module CliColors =
А что это за модуль такой?

2021-10-27 11:12 UTC, gsvgit commented on src/BigInt/Interpreter.fs
> +            | _ -> failwith "impossible case"
Какой?

2021-10-27 11:12 UTC, gsvgit commented on src/BigInt/bigIntFunctions.fs
> +            else
А почему не elif ?

2021-10-27 11:12 UTC, gsvgit commented on tests/BigInt.UnitTests/bigIntFunctionsTest.fs
> +                testProperty "isEqual test" <| fun _ ->
Что-то с тестами лучше не стало.

2021-11-02 08:25 UTC, gsvgit approved these changes

2021-11-03 14:05 UTC, merged